name: Build and lint
on:
  workflow_dispatch:
jobs:
  linux-cachyos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build (GCC)
      id: makepkg
      uses: CachyOS/pkgbuild-action@master
      with:
        envvars: "_HZ_ticks=750 _preempt=voluntary _hugepage=madvise _processor_opt=skylake _use_auto_optimization= _tickrate=idle _build_debug="
        pkgdir: "linux-cachyos-build"
        namcapExcludeRules: "invalidstartdir"
        makepkgArgs: "--skipchecksums --skippgpcheck --noconfirm -s --printsrcinfo > .SRCINFO"
